[package]
name = "nbuild-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.15.4"
target-spec = "1.4.0"
tracing = "0.1.37"

[dev-dependencies]
pretty_assertions = "1.3.0"
