[package]
name = "cargo-nbuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nbuild-core = { path = "../nbuild-core" }
runix = "0.1.1"
tokio = "1.28.1"
